-- 20260907120500_site_001_init.sql
-- The site namespace: facts and configuration about the website.
--
-- business_location and gbp carry a REVIEW flag (Abdullah). They are
-- built as written rather than blocking the rest; his input is
-- gathered when each table's populate script is written. Under
-- one-script-per-table an unwritten script costs nothing, whereas a
-- missing table is an unknown gap.
create schema if not exists site;

-- One row per site.
create table site.structure (
    domain_id             bigint primary key
                              references meta.site(domain_id)
                              on delete cascade,
    cms                   text,
    cms_sub_shape         text,
    url_format            text,
    url_conventions       text,
    canonical_host        text,
    subdomain_policy      text,
    site_type             text check (site_type in
                              ('aggregator','brochure','ecommerce',
                               'marketplace')),
    top_nav               text[],
    hub_spoke_pattern     text,
    service_area_strategy text,
    location_url_pattern  text,
    parallel_systems      text,
    linking_rules         text,
    constraints           text,
    blog_strategy         text,
    indexability          text,
    sitemap_page_count    int,
    unlisted_pages        text,
    source                text not null,
    notes                 text,
    created_at            timestamptz not null default now(),
    updated_at            timestamptz not null default now()
);

comment on table site.structure is
    'Crawl notes are a document, not a column here -- site-structure.md, '
    'doc_class observation, generated by the P0 skill at onboarding.';

-- One row per site. Read by a skill before a crawl.
create table site.crawl_config (
    domain_id             bigint primary key
                              references meta.site(domain_id)
                              on delete cascade,
    bot_protection        text,
    custom_ua_required    boolean not null default false,
    user_agent            text,
    required_ip           text,
    sf_config             text,
    scope_path            text,
    sitemap_url           text,
    excluded_url_patterns text[],
    slug_stop_segments    text[],
    source                text not null,
    notes                 text,
    created_at            timestamptz not null default now(),
    updated_at            timestamptz not null default now()
);

comment on table site.crawl_config is
    'Queried, not embedded. A skill reads this before a crawl; it '
    'should never join the embedded corpus. Three fields cover the '
    'access combinations -- a client may require a whitelisted IP, a '
    'custom user agent, or both. Any missing means a crawl that fails '
    'or silently returns nothing: Cloudflare on kitchenguard.com cost '
    'a full wrong pass with the working agent recorded only in a note.';

-- REVIEW: Abdullah. One row per physical place.
create table site.business_location (
    business_location_id uuid primary key default gen_random_uuid(),
    domain_id            bigint not null
                             references meta.site(domain_id)
                             on delete cascade,
    name                 text not null,
    street_address       text,
    address_published    boolean not null default false,
    telephone            text,
    hours                text,
    map_url              text,
    review_rating        numeric,
    review_count         int,
    tenure               text,
    market_id            uuid references brand.market(market_id),
    source               text not null,
    notes                text,
    created_at           timestamptz not null default now(),
    updated_at           timestamptz not null default now()
);

create index business_location_domain_idx
    on site.business_location (domain_id);

comment on table site.business_location is
    'A location is not a market. BusBank has one business location and '
    '128 markets. Linked by market_id, not the DataForSEO code.';

comment on column site.business_location.address_published is
    'false for a service-area business.';

comment on column site.business_location.tenure is
    'How long this operator has traded. Not brand.identity.founded_year.';

-- REVIEW: Abdullah. One row per listing.
create table site.gbp (
    gbp_id               uuid primary key default gen_random_uuid(),
    domain_id            bigint not null
                             references meta.site(domain_id)
                             on delete cascade,
    business_location_id uuid
                             references site.business_location(
                                 business_location_id),
    gbp_name             text,
    gbp_cid              text,
    gbp_place_id         text,
    connected            boolean not null default false,
    jepto_dataset        text,
    jepto_location_id    text,
    search_lat           double precision,
    search_lng           double precision,
    primary_geo          text,
    store_code           text,
    status               text not null default 'active'
                             check (status in ('active','archived')),
    local_seo_in_scope   boolean not null default false,
    source               text not null,
    notes                text,
    created_at           timestamptz not null default now(),
    updated_at           timestamptz not null default now()
);

create index gbp_domain_idx on site.gbp (domain_id);
create index gbp_location_idx on site.gbp (business_location_id);

comment on table site.gbp is
    'Repeating, deliberately. The prior shipped table was one profile '
    'per property, collapsed from a design allowing many, and the cost '
    'was a Jepto-connected Kitchen Guard location with no matching '
    'property. Three KitchenGuard territories need the original '
    'cardinality.';

comment on column site.gbp.connected is
    'Routes Jepto vs DataForSEO.';

comment on column site.gbp.search_lat is
    'A search anchor, not the address.';
