"""Declarative migration manifest for the DataForSEO table rename + standardization.

Each Migration entry tells scripts/migrate_dataforseo_tables.py what to do for
one logical table. Three shapes:

1. Rename: old_name is set; new_name differs. Backs up old, creates new,
   copies data, drops old.
2. In-place schema update: old_name == new_name. Backs up, ALTER TABLE ADD
   COLUMN for new metadata columns.
3. New table: old_name is None. Just creates the new table.

Historical-row defaults when copying old data:
- endpoint_mode = "live" (all legacy rows were live calls)
- task_id = NULL (not captured historically)
- domain_id = NULL (can't retroactively resolve)
- domain = preserved if old table has `domain` column, else NULL
"""

from __future__ import annotations

from dataclasses import dataclass


BACKUP_SUFFIX = "_backup_04-20-2026"


@dataclass(frozen=True)
class Migration:
    """One table's migration config."""

    new_name: str
    new_schema: str  # SQL column list (starts with METADATA_BLOCK_SQL, then endpoint cols)
    old_name: str | None = None
    drop_project_id: bool = False
    preserve_domain_column: bool = True
    clustering_fields: tuple[str, ...] = ("domain_id", "job_id")
    partition_field: str = "ingest_timestamp"


# The metadata block that every new table starts with.
METADATA_BLOCK_SQL = """\
  job_id STRING NOT NULL OPTIONS(description="UUID generated by caller via generate_job_id(). Groups all rows fetched in one logical job (across multiple endpoints/targets). Indexed via BQ clustering."),
  upload_id STRING NOT NULL OPTIONS(description="UUID generated per load_table_from_dataframe() batch via generate_upload_id(). Links rows to Logs.upload_events for auditability."),
  ingest_timestamp TIMESTAMP NOT NULL OPTIONS(description="UTC timestamp the row was written to BQ. Partition field (daily partitions)."),
  domain_id INT64 OPTIONS(description="Foreign key to Meta.domains. Set by the caller's domain= or domain_id= argument; nullable if caller opted out (domain=None). Cluster field."),
  domain STRING OPTIONS(description="Canonical domain string (from Meta.domains lookup). Represents caller context, not per-row API data."),
  task_id STRING OPTIONS(description="DataForSEO task ID (tasks[0].id) from the API response that produced this row. Nullable for legacy rows."),
  endpoint_mode STRING NOT NULL OPTIONS(description="'live' or 'standard'. Identifies whether the row came from the synchronous /live call or the async task_post + task_get workflow. Most endpoints only support one mode."),
"""


# -----------------------------------------------------------------------------
# Per-endpoint column definitions.
# Types are derived from each endpoint's _cast_types() method. Columns not
# explicitly cast default to STRING. `task_id` and (where it would collide)
# `domain` are excluded from endpoint-specific cols because they live in the
# metadata block.
# -----------------------------------------------------------------------------

BACKLINKS_BACKLINKS_COLS = """\
  url STRING OPTIONS(description="Target URL or domain that was queried (the backlink destination being analyzed)."),
  type STRING OPTIONS(description="Type of backlink source page (e.g., anchor, image, meta, canonical, alternate, redirect)."),
  item_type STRING OPTIONS(description="Specific link element type as classified by DataForSEO."),
  attributes STRING OPTIONS(description="JSON-serialized array of HTML rel attribute values on the link (e.g., ['nofollow','noopener'])."),
  original BOOL OPTIONS(description="Whether this is the original link (vs. a duplicate from grouping)."),
  domain_from STRING OPTIONS(description="Referring domain hosting the backlink."),
  url_from STRING OPTIONS(description="Full URL of the referring page containing the backlink."),
  url_from_https BOOL OPTIONS(description="Whether the referring URL uses HTTPS."),
  tld_from STRING OPTIONS(description="Top-level domain of the referring domain."),
  domain_from_rank INT64 OPTIONS(description="DataForSEO rank of the referring domain (0-1000 scale)."),
  domain_from_platform_type STRING OPTIONS(description="JSON-serialized array of platform types detected for the referring domain (e.g., ['cms','blogs'])."),
  domain_from_is_ip BOOL OPTIONS(description="Whether the referring domain is a raw IP address rather than a hostname."),
  domain_from_ip STRING OPTIONS(description="IP address of the referring domain."),
  domain_from_country STRING OPTIONS(description="ISO country code associated with the referring domain's server."),
  domain_to STRING OPTIONS(description="Destination domain of the backlink."),
  backlink_to STRING OPTIONS(description="Destination URL the backlink points to (renamed from API's url_to)."),
  backlink_to_https BOOL OPTIONS(description="Whether the destination URL uses HTTPS."),
  backlink_to_status_code INT64 OPTIONS(description="HTTP status code returned by the destination URL."),
  backlink_to_spam_score INT64 OPTIONS(description="DataForSEO spam score (0-100) of the destination URL."),
  backlink_to_redirect_target STRING OPTIONS(description="If the destination URL redirects, the final redirect target URL."),
  dofollow BOOL OPTIONS(description="Whether the link passes link equity (no nofollow rel attribute)."),
  backlink_spam_score INT64 OPTIONS(description="DataForSEO spam score (0-100) of this individual backlink."),
  is_broken BOOL OPTIONS(description="Whether the backlink is broken (referring page or target returns an error)."),
  is_indirect_link BOOL OPTIONS(description="Whether the link reaches the target via an intermediate redirect chain."),
  indirect_link_path STRING OPTIONS(description="JSON-serialized array describing the redirect path when is_indirect_link is true."),
  anchor STRING OPTIONS(description="Anchor text of the backlink."),
  alt STRING OPTIONS(description="alt attribute text when the backlink is an image."),
  image_url STRING OPTIONS(description="Source URL of the image when the backlink is an image link."),
  text_pre STRING OPTIONS(description="Text appearing immediately before the anchor on the referring page."),
  text_post STRING OPTIONS(description="Text appearing immediately after the anchor on the referring page."),
  semantic_location STRING OPTIONS(description="Semantic region of the referring page where the link is located (e.g., content, nav, footer, sidebar)."),
  first_seen TIMESTAMP OPTIONS(description="UTC timestamp when the backlink was first detected by DataForSEO."),
  prev_seen TIMESTAMP OPTIONS(description="UTC timestamp of the previous crawl that saw the backlink."),
  last_seen TIMESTAMP OPTIONS(description="UTC timestamp of the most recent crawl that saw the backlink."),
  is_new BOOL OPTIONS(description="Whether the backlink is newly discovered in the latest crawl."),
  is_lost BOOL OPTIONS(description="Whether the backlink was present previously but not found in the latest crawl."),
  rank INT64 OPTIONS(description="DataForSEO rank (0-1000) of this individual backlink."),
  page_from_rank INT64 OPTIONS(description="DataForSEO rank (0-1000) of the referring page."),
  page_from_keywords_count_top_3 INT64 OPTIONS(description="Number of organic keywords for which the referring page ranks in positions 1-3."),
  page_from_keywords_count_top_10 INT64 OPTIONS(description="Number of organic keywords for which the referring page ranks in positions 1-10."),
  page_from_keywords_count_top_100 INT64 OPTIONS(description="Number of organic keywords for which the referring page ranks in positions 1-100."),
  page_from_title STRING OPTIONS(description="<title> of the referring page."),
  page_from_status_code INT64 OPTIONS(description="HTTP status code returned by the referring page."),
  page_from_external_links INT64 OPTIONS(description="Total number of external outbound links on the referring page."),
  page_from_internal_links INT64 OPTIONS(description="Total number of internal links on the referring page."),
  page_from_size INT64 OPTIONS(description="Size of the referring page's HTML in bytes."),
  page_from_encoding STRING OPTIONS(description="Character encoding declared by the referring page."),
  page_from_language STRING OPTIONS(description="ISO language code detected for the referring page."),
  links_count INT64 OPTIONS(description="Number of links from the referring page to the target."),
  group_count INT64 OPTIONS(description="Number of backlinks grouped under this representative row when grouping is enabled.")
"""

BACKLINKS_BULK_PAGES_SUMMARY_COLS = """\
  url STRING OPTIONS(description="Target page URL as submitted to the API (one row per target)."),
  backlinks INT64 OPTIONS(description="Total number of backlinks pointing to the target page."),
  referring_domains INT64 OPTIONS(description="Count of unique referring domains linking to the target."),
  referring_domains_nofollow INT64 OPTIONS(description="Count of referring domains whose links are all rel='nofollow'."),
  referring_main_domains INT64 OPTIONS(description="Count of unique referring root domains (subdomains collapsed)."),
  referring_main_domains_nofollow INT64 OPTIONS(description="Count of referring root domains whose links are all rel='nofollow'."),
  rank INT64 OPTIONS(description="DataForSEO page rank (0-1000 scale) computed from the backlink graph."),
  main_domain_rank INT64 OPTIONS(description="DataForSEO rank (0-1000 scale) of the target's root domain."),
  spam_score FLOAT64 OPTIONS(description="DataForSEO spam score (0-100 percentage scale) of the target's backlink profile."),
  referring_ips INT64 OPTIONS(description="Count of unique IP addresses hosting referring pages."),
  referring_subnets INT64 OPTIONS(description="Count of unique /24 subnets hosting referring pages."),
  referring_pages INT64 OPTIONS(description="Count of unique referring pages (URLs) linking to the target."),
  referring_pages_nofollow INT64 OPTIONS(description="Count of referring pages whose outbound link to the target carries rel='nofollow' (page-level nofollow count — distinct from the link-attribute-level nofollow column below)."),
  dofollow INT64 OPTIONS(description="Derived count of dofollow backlinks, computed as backlinks - referring_links_attributes.nofollow."),
  nofollow INT64 OPTIONS(description="Count of backlinks carrying the rel='nofollow' link attribute (link-attribute level — distinct from the page-level referring_pages_nofollow column above)."),
  referring_links_attributes STRING OPTIONS(description="Stringified JSON dict of link-attribute counts (e.g. {'noopener': N, 'nofollow': N, 'ugc': N, 'sponsored': N, 'external': N, ...})."),
  broken_backlinks INT64 OPTIONS(description="Count of backlinks to the target that are currently broken."),
  broken_pages INT64 OPTIONS(description="Count of referring pages that are currently broken (404/5xx)."),
  first_seen TIMESTAMP OPTIONS(description="UTC timestamp of the first time DataForSEO observed a backlink to this target."),
  lost_date TIMESTAMP OPTIONS(description="UTC timestamp of the last observed backlink if all links have since been lost; NULL while the target still has live backlinks.")
"""

BACKLINKS_SUMMARY_COLS = """\
  target STRING OPTIONS(description="The domain or URL that was queried (echoed from the request)."),
  target_type STRING OPTIONS(description="Classification of the target — 'domain' if no path component, 'url' if a specific page path was queried. Derived client-side."),
  rank INT64 OPTIONS(description="DataForSEO rank score (0-1000) representing the target's backlink authority."),
  backlinks INT64 OPTIONS(description="Total number of backlinks pointing to the target."),
  backlinks_spam_score INT64 OPTIONS(description="Aggregate spam score (0-100) computed across all referring backlinks — the spammy-ness of the link profile, not of the target itself."),
  target_spam_score INT64 OPTIONS(description="Spam score (0-100) for the target page or domain's own content (from the API's nested info block)."),
  crawled_pages INT64 OPTIONS(description="Number of pages DataForSEO has crawled on the target (data-coverage signal)."),
  referring_domains INT64 OPTIONS(description="Number of unique domains that link to the target."),
  referring_domains_nofollow INT64 OPTIONS(description="Number of referring domains where all links are nofollow."),
  referring_main_domains INT64 OPTIONS(description="Number of unique root/main domains (subdomains collapsed) linking to the target."),
  referring_main_domains_nofollow INT64 OPTIONS(description="Number of referring main domains where all links are nofollow."),
  referring_ips INT64 OPTIONS(description="Number of unique IP addresses hosting referring domains."),
  referring_subnets INT64 OPTIONS(description="Number of unique class-C subnets hosting referring domains."),
  referring_pages INT64 OPTIONS(description="Number of unique referring pages linking to the target."),
  referring_pages_nofollow INT64 OPTIONS(description="Number of referring pages where all links to the target are nofollow."),
  referring_links_tld STRING OPTIONS(description="Stringified JSON dict-of-counters mapping each TLD to its referring-link count."),
  referring_links_types STRING OPTIONS(description="Stringified JSON dict-of-counters mapping link type (e.g. anchor, image, canonical) to count."),
  referring_links_attributes STRING OPTIONS(description="Stringified JSON dict-of-counters mapping link attribute (e.g. nofollow, ugc, sponsored) to count."),
  referring_links_platform_types STRING OPTIONS(description="Stringified JSON dict-of-counters mapping platform type (e.g. blogs, cms, ecommerce) to count."),
  referring_links_semantic_locations STRING OPTIONS(description="Stringified JSON dict-of-counters mapping semantic page location (e.g. footer, article, nav) to count."),
  referring_links_countries STRING OPTIONS(description="Stringified JSON dict-of-counters mapping ISO country code of referring domains to count."),
  internal_links_count INT64 OPTIONS(description="Total internal links found on crawled pages of the target."),
  external_links_count INT64 OPTIONS(description="Total external (outbound) links found on crawled pages of the target."),
  broken_backlinks INT64 OPTIONS(description="Number of backlinks pointing to broken pages on the target."),
  broken_pages INT64 OPTIONS(description="Number of broken pages on the target that receive backlinks."),
  first_seen TIMESTAMP OPTIONS(description="UTC timestamp of the earliest backlink DataForSEO has recorded for the target."),
  lost_date TIMESTAMP OPTIONS(description="UTC timestamp when the target's backlink profile was last marked as lost (NULL if still live).")
"""

SERP_GOOGLE_ORGANIC_COLS = """\
  keyword STRING OPTIONS(description="The search query submitted to Google."),
  serp_datetime TIMESTAMP OPTIONS(description="UTC timestamp of when DataForSEO collected the SERP."),
  se_domain STRING OPTIONS(description="Google search engine domain used (e.g. google.com, google.co.uk)."),
  location_code INT64 OPTIONS(description="DataForSEO location code (e.g. 2840 for United States)."),
  language_code STRING OPTIONS(description="Language code used for the query (e.g. en)."),
  device STRING OPTIONS(description="Device type: desktop or mobile."),
  os STRING OPTIONS(description="Operating system used for the SERP fetch (e.g. windows, macos, android)."),
  se_results_count INT64 OPTIONS(description="Total estimated result count reported by Google for this query."),
  check_url STRING OPTIONS(description="Google URL that reproduces this SERP in a browser."),
  item_types STRING OPTIONS(description="Stringified JSON array of all SERP feature types present on this keyword's SERP. Same value repeated on every row for the keyword; contrast with singular item_type, which is per-row."),
  refinement_chips STRING OPTIONS(description="Stringified JSON of Google's query-refinement chip suggestions (the filter pills shown above results). NULL if none."),
  item_type STRING OPTIONS(description="This row's SERP feature type. Common values: organic, featured_snippet, knowledge_graph, people_also_ask, local_pack, related_searches, video, images, top_stories, paid, shopping, answer_box, twitter, map, carousel."),
  rank_group INT64 OPTIONS(description="Group rank within the same item_type (1-based; same-type items share a sequence)."),
  rank_absolute INT64 OPTIONS(description="Absolute rank across the full SERP, counting every feature from top to bottom (1-based)."),
  page INT64 OPTIONS(description="Google results page this item appears on (1 = first page)."),
  position STRING OPTIONS(description="SERP column position: 'left' (main results column) or 'right' (sidebar, e.g. knowledge panel)."),
  url STRING OPTIONS(description="Ranking URL for this SERP item (populated for organic, some featured_snippet, and other URL-bearing item types; NULL for items without a URL like related_searches or refinement_chips)."),
  title STRING OPTIONS(description="Title text of this SERP item (populated for organic, featured_snippet, local_pack, knowledge_graph, etc.; NULL for item types without a title)."),
  description STRING OPTIONS(description="Snippet/description text of this SERP item (populated for organic, local_pack, knowledge_graph, etc.; NULL for item types without descriptive text)."),
  data STRING OPTIONS(description="Stringified JSON of the SERP-level payload with the items array stripped out — includes fields like spell, pages_count, etc. Same value repeated on every row for the keyword."),
  item STRING OPTIONS(description="Stringified JSON of the full nested payload for this specific SERP item (the raw DataForSEO item object — title, url, description, expanded_element, links, rectangle, etc., depending on item_type).")
"""

DATAFORSEO_LABS_KEYWORD_SUGGESTIONS_COLS = """\
  se_type STRING OPTIONS(description="Search engine type (e.g. 'google')."),
  seed_keyword STRING OPTIONS(description="The seed keyword the suggestions were generated from."),
  keyword STRING OPTIONS(description="The suggested keyword."),
  location_code INT64 OPTIONS(description="DataForSEO location code (e.g. 2840 for US)."),
  language_code STRING OPTIONS(description="ISO language code (e.g. 'en')."),
  search_volume INT64 OPTIONS(description="Average monthly Google search volume for the keyword."),
  competition FLOAT64 OPTIONS(description="Google Ads competition index, 0.0-1.0."),
  competition_level STRING OPTIONS(description="Competition bucket: 'LOW', 'MEDIUM', or 'HIGH'."),
  cpc FLOAT64 OPTIONS(description="Average cost-per-click in USD."),
  low_top_of_page_bid FLOAT64 OPTIONS(description="Low range top-of-page bid estimate (USD)."),
  high_top_of_page_bid FLOAT64 OPTIONS(description="High range top-of-page bid estimate (USD)."),
  categories STRING OPTIONS(description="Stringified JSON array of Google product/service category IDs."),
  monthly_searches STRING OPTIONS(description="Stringified JSON array of {year, month, search_volume} objects (12 months of history)."),
  search_volume_trend_monthly FLOAT64 OPTIONS(description="Percentage delta in search volume vs. prior month."),
  search_volume_trend_quarterly FLOAT64 OPTIONS(description="Percentage delta in search volume vs. prior quarter."),
  search_volume_trend_yearly FLOAT64 OPTIONS(description="Percentage delta in search volume vs. prior year."),
  keyword_info_last_updated_time TIMESTAMP OPTIONS(description="Freshness signal for the keyword_info block (UTC)."),
  core_keyword STRING OPTIONS(description="Canonical/root keyword the suggestion is grouped under."),
  keyword_difficulty INT64 OPTIONS(description="DataForSEO keyword difficulty score, 0-100."),
  detected_language STRING OPTIONS(description="Language auto-detected from the keyword text."),
  is_another_language BOOL OPTIONS(description="True if detected_language differs from the requested language_code."),
  words_count INT64 OPTIONS(description="Number of words in the suggested keyword."),
  main_intent STRING OPTIONS(description="Primary search intent ('informational', 'navigational', 'commercial', 'transactional')."),
  foreign_intent STRING OPTIONS(description="Comma-joined string of secondary intent labels for this keyword."),
  search_intent_last_updated_time TIMESTAMP OPTIONS(description="Freshness signal for the search_intent_info block (UTC)."),
  avg_backlinks FLOAT64 OPTIONS(description="Average backlinks across top-ranking SERP results (from avg_backlinks_info.backlinks)."),
  avg_dofollow FLOAT64 OPTIONS(description="Average count of dofollow backlinks across top-ranking SERP results."),
  avg_referring_pages FLOAT64 OPTIONS(description="Average number of referring pages across top-ranking SERP results."),
  avg_referring_domains FLOAT64 OPTIONS(description="Average number of referring domains across top-ranking SERP results."),
  avg_referring_main_domains FLOAT64 OPTIONS(description="Average number of referring main (root) domains across top-ranking SERP results."),
  avg_rank FLOAT64 OPTIONS(description="Average DataForSEO page rank of top-ranking SERP results."),
  avg_main_domain_rank FLOAT64 OPTIONS(description="Average DataForSEO main-domain rank of top-ranking SERP results."),
  avg_backlinks_last_updated_time TIMESTAMP OPTIONS(description="Freshness signal for the avg_backlinks_info block (UTC).")
"""

DATAFORSEO_LABS_RELATED_KEYWORDS_COLS = """\
  seed_keyword STRING OPTIONS(description="The seed keyword submitted to the endpoint."),
  related_keyword STRING OPTIONS(description="The keyword represented by this row — the node in the related-keywords traversal."),
  depth INT64 OPTIONS(description="Traversal depth: 0 for the seed keyword itself, 1+ for related keywords at each expansion level."),
  location_code INT64 OPTIONS(description="DataForSEO location code (e.g., 2840 for US)."),
  language_code STRING OPTIONS(description="Language code (e.g., en)."),
  search_volume INT64 OPTIONS(description="Average monthly search volume for related_keyword."),
  cpc FLOAT64 OPTIONS(description="Average cost-per-click (USD) in Google Ads."),
  competition FLOAT64 OPTIONS(description="Google Ads competition score (0.0-1.0)."),
  competition_level STRING OPTIONS(description="Bucketed competition label (LOW, MEDIUM, HIGH)."),
  low_top_of_page_bid FLOAT64 OPTIONS(description="Low range top-of-page bid estimate (USD)."),
  high_top_of_page_bid FLOAT64 OPTIONS(description="High range top-of-page bid estimate (USD)."),
  monthly_searches STRING OPTIONS(description="Stringified JSON array of {year, month, search_volume} objects (12 months)."),
  search_volume_trend_monthly FLOAT64 OPTIONS(description="Month-over-month percentage change in search volume."),
  search_volume_trend_quarterly FLOAT64 OPTIONS(description="Quarter-over-quarter percentage change in search volume."),
  search_volume_trend_yearly FLOAT64 OPTIONS(description="Year-over-year percentage change in search volume."),
  keyword_info_last_updated_time TIMESTAMP OPTIONS(description="When DataForSEO last refreshed the keyword_info block."),
  core_keyword STRING OPTIONS(description="The canonical 'core' keyword in the synonym cluster this keyword belongs to."),
  keyword_difficulty INT64 OPTIONS(description="DataForSEO keyword difficulty score (0-100)."),
  detected_language STRING OPTIONS(description="Language DataForSEO detected for the keyword text."),
  is_other_language BOOL OPTIONS(description="True if detected language differs from the requested language_code (sources the API's is_another_language field — historical column naming)."),
  serp_item_types STRING OPTIONS(description="Stringified JSON array of SERP feature types present on the crawled SERP."),
  se_results_count INT64 OPTIONS(description="Google's reported total results count for the SERP."),
  serp_last_updated_time TIMESTAMP OPTIONS(description="When DataForSEO last crawled the SERP for this keyword."),
  serp_info_check_url STRING OPTIONS(description="The Google SERP URL DataForSEO crawled for this keyword."),
  serp_info_previous_updated_time TIMESTAMP OPTIONS(description="The prior crawl time for the SERP (useful for change detection)."),
  backlinks FLOAT64 OPTIONS(description="Average number of backlinks pointing to the top-ranking pages."),
  dofollow FLOAT64 OPTIONS(description="Average number of dofollow backlinks to the top-ranking pages."),
  referring_pages FLOAT64 OPTIONS(description="Average number of referring pages for the top-ranking pages."),
  referring_domains FLOAT64 OPTIONS(description="Average number of referring domains for the top-ranking pages."),
  referring_main_domains FLOAT64 OPTIONS(description="Average number of referring main (root) domains for the top-ranking pages."),
  main_domain_rank FLOAT64 OPTIONS(description="Average DataForSEO rank of the main domains of the top-ranking pages."),
  avg_rank FLOAT64 OPTIONS(description="Average DataForSEO page rank across the top-ranking pages (from avg_backlinks_info.rank)."),
  avg_backlinks_last_updated_time TIMESTAMP OPTIONS(description="When DataForSEO last refreshed the avg_backlinks_info block."),
  search_intent_main STRING OPTIONS(description="Primary search intent label (e.g., informational, transactional, commercial, navigational)."),
  foreign_intent STRING OPTIONS(description="Secondary/additional intent labels, comma-joined."),
  search_intent_last_updated_time TIMESTAMP OPTIONS(description="When DataForSEO last refreshed the search_intent_info block."),
  related_keywords STRING OPTIONS(description="Stringified JSON array of related-keyword strings for this row's keyword — the signature payload of the endpoint, representing the next-depth neighbors of related_keyword in the traversal graph.")
"""

DATAFORSEO_LABS_RANKED_KEYWORDS_COLS = """\
  keyword STRING OPTIONS(description="The keyword the target domain ranks for."),
  rank INT64 OPTIONS(description="SERP position in the organic result list (may differ from rank_absolute)."),
  url STRING OPTIONS(description="The ranked URL on the target domain for this keyword."),
  search_volume INT64 OPTIONS(description="Average monthly search volume for the keyword."),
  keyword_difficulty INT64 OPTIONS(description="Overall keyword difficulty score (0-100)."),
  national_location_code INT64 OPTIONS(description="Location code passed in the API request (national/country-level)."),
  traffic_volume FLOAT64 OPTIONS(description="Estimated monthly organic traffic (ETV) this ranking drives to the URL."),
  keyword_location_code INT64 OPTIONS(description="Location code attached to the keyword data in the API response."),
  language_code STRING OPTIONS(description="Language code for the keyword (e.g., en)."),
  main_domain STRING OPTIONS(description="Root/main domain of the ranked URL."),
  cpc FLOAT64 OPTIONS(description="Average Google Ads cost-per-click in USD for the keyword."),
  low_top_of_page_bid FLOAT64 OPTIONS(description="Low-range top-of-page bid estimate (USD)."),
  high_top_of_page_bid FLOAT64 OPTIONS(description="High-range top-of-page bid estimate (USD)."),
  competition FLOAT64 OPTIONS(description="Google Ads competition index for the keyword (0-1)."),
  competition_level STRING OPTIONS(description="Google Ads competition bucket (LOW, MEDIUM, HIGH)."),
  categories STRING OPTIONS(description="Stringified JSON array of Google product/service category IDs."),
  monthly_searches STRING OPTIONS(description="Stringified JSON array of per-month historical search volume."),
  search_volume_trend_monthly FLOAT64 OPTIONS(description="Percent change in search volume vs. previous month."),
  search_volume_trend_quarterly FLOAT64 OPTIONS(description="Percent change in search volume vs. previous quarter."),
  search_volume_trend_yearly FLOAT64 OPTIONS(description="Percent change in search volume vs. previous year."),
  keyword_info_last_updated_time TIMESTAMP OPTIONS(description="When the keyword_info block was last refreshed."),
  core_keyword STRING OPTIONS(description="Canonical core keyword that this keyword is a variant of."),
  detected_language STRING OPTIONS(description="Language auto-detected for the keyword."),
  is_another_language BOOL OPTIONS(description="True if detected language differs from requested language_code."),
  rank_absolute INT64 OPTIONS(description="Absolute SERP position considering all SERP features (ads, snippets, etc.)."),
  position STRING OPTIONS(description="SERP column the result appears in ('left' or 'right')."),
  serp_keyword_difficulty INT64 OPTIONS(description="Ranked-keywords-specific difficulty score derived from the live SERP (distinct from keyword_difficulty)."),
  serp_item_types STRING OPTIONS(description="Stringified JSON array of SERP element types present on the results page."),
  se_results_count INT64 OPTIONS(description="Total number of organic results Google reports for the keyword."),
  main_intent STRING OPTIONS(description="Primary search intent classification."),
  foreign_intent STRING OPTIONS(description="Comma-joined list of secondary search intents."),
  search_intent_last_updated_time TIMESTAMP OPTIONS(description="When the search_intent_info block was last refreshed."),
  avg_backlinks FLOAT64 OPTIONS(description="Average number of backlinks across the top-ranking URLs for this keyword."),
  avg_referring_domains FLOAT64 OPTIONS(description="Average referring domains across the top-ranking URLs."),
  avg_referring_main_domains FLOAT64 OPTIONS(description="Average referring main (root) domains across the top-ranking URLs."),
  avg_rank FLOAT64 OPTIONS(description="Average DataForSEO page rank across the top-ranking URLs."),
  avg_main_domain_rank FLOAT64 OPTIONS(description="Average DataForSEO main-domain rank across the top-ranking URLs."),
  avg_backlinks_last_updated_time TIMESTAMP OPTIONS(description="When the avg_backlinks_info block was last refreshed."),
  serp_item_type STRING OPTIONS(description="Type of SERP element the ranked URL is (e.g., organic, featured_snippet)."),
  serp_item_title STRING OPTIONS(description="Title text of the ranked SERP result."),
  serp_item_description STRING OPTIONS(description="Snippet/description text of the ranked SERP result."),
  is_featured_snippet BOOL OPTIONS(description="True if the ranked result IS the featured snippet for the keyword."),
  estimated_paid_traffic_cost FLOAT64 OPTIONS(description="Estimated monthly cost (USD) to acquire equivalent paid traffic for this ranking."),
  previous_rank_absolute INT64 OPTIONS(description="Prior rank_absolute for the same keyword before the latest crawl."),
  rank_is_new BOOL OPTIONS(description="True if this keyword appeared as a new ranking since the last crawl."),
  rank_is_up BOOL OPTIONS(description="True if the rank improved since the last crawl."),
  rank_is_down BOOL OPTIONS(description="True if the rank dropped since the last crawl."),
  serp_item_referring_domains INT64 OPTIONS(description="Referring domains pointing to the specific ranked URL."),
  serp_item_referring_main_domains INT64 OPTIONS(description="Referring main (root) domains pointing to the specific ranked URL."),
  serp_item_backlinks INT64 OPTIONS(description="Total backlinks pointing to the specific ranked URL."),
  serp_item_page_rank INT64 OPTIONS(description="DataForSEO page rank of the specific ranked URL."),
  serp_item_main_domain_rank INT64 OPTIONS(description="DataForSEO main-domain rank of the ranked URL's root domain."),
  is_lost BOOL OPTIONS(description="True if the ranking was lost (URL no longer ranks for this keyword) since the last crawl.")
"""

DATAFORSEO_LABS_KEYWORD_OVERVIEW_COLS = """\
  keyword STRING OPTIONS(description="The input keyword (lowercased by DataForSEO)."),
  location_code INT64 OPTIONS(description="DataForSEO location code (e.g., 2840 = United States)."),
  language_code STRING OPTIONS(description="Language of the search market (e.g., 'en')."),
  search_volume INT64 OPTIONS(description="Average monthly search volume for this keyword."),
  competition FLOAT64 OPTIONS(description="Relative competition from Google Ads, 0.0-1.0."),
  competition_level STRING OPTIONS(description="Competition bucket: LOW, MEDIUM, or HIGH."),
  cpc FLOAT64 OPTIONS(description="Historical average cost-per-click in USD."),
  low_top_of_page_bid FLOAT64 OPTIONS(description="Minimum bid (USD) to appear at top of page."),
  high_top_of_page_bid FLOAT64 OPTIONS(description="Maximum bid (USD) to appear at top of page."),
  categories STRING OPTIONS(description="Stringified JSON array of Google product/service category IDs."),
  monthly_searches STRING OPTIONS(description="Stringified JSON list of {year, month, search_volume} entries (12 months of history)."),
  search_volume_trend_monthly FLOAT64 OPTIONS(description="Percentage change in search volume vs. previous month."),
  search_volume_trend_quarterly FLOAT64 OPTIONS(description="Percentage change in search volume vs. previous quarter."),
  search_volume_trend_yearly FLOAT64 OPTIONS(description="Percentage change in search volume vs. previous year."),
  keyword_info_last_updated_time TIMESTAMP OPTIONS(description="Data-freshness signal: when DataForSEO last refreshed keyword volume/CPC metrics."),
  core_keyword STRING OPTIONS(description="Main keyword of the cluster this keyword belongs to."),
  keyword_difficulty INT64 OPTIONS(description="Estimated difficulty of ranking in Google's top 10 (0-100)."),
  detected_language STRING OPTIONS(description="Language detected from the keyword text itself."),
  is_another_language BOOL OPTIONS(description="True when detected_language does not match the requested language_code."),
  main_intent STRING OPTIONS(description="Primary search intent: informational, navigational, commercial, or transactional."),
  foreign_intent STRING OPTIONS(description="Secondary intents as a comma-joined string (flattened from API array)."),
  search_intent_last_updated_time TIMESTAMP OPTIONS(description="Data-freshness signal: when intent classification was last updated."),
  avg_backlinks FLOAT64 OPTIONS(description="Aggregate backlink metric of top-ranking pages: avg total backlinks."),
  avg_dofollow FLOAT64 OPTIONS(description="Aggregate backlink metric: avg dofollow backlinks."),
  avg_referring_pages FLOAT64 OPTIONS(description="Aggregate backlink metric: avg referring pages."),
  avg_referring_domains FLOAT64 OPTIONS(description="Aggregate backlink metric: avg referring domains."),
  avg_referring_main_domains FLOAT64 OPTIONS(description="Aggregate backlink metric: avg referring root/main domains."),
  avg_rank FLOAT64 OPTIONS(description="Aggregate backlink metric: avg DataForSEO page rank."),
  avg_main_domain_rank FLOAT64 OPTIONS(description="Aggregate backlink metric: avg DataForSEO root-domain rank."),
  avg_backlinks_last_updated_time TIMESTAMP OPTIONS(description="Data-freshness signal: when aggregate backlink metrics were last refreshed.")
"""

DATAFORSEO_LABS_SEARCH_INTENT_COLS = """\
  keyword STRING OPTIONS(description="The keyword that was classified."),
  search_intent STRING OPTIONS(description="Primary intent label assigned to the keyword — one of informational, commercial, navigational, transactional."),
  intent_probability FLOAT64 OPTIONS(description="Confidence score (0-1) for the primary search_intent label."),
  secondary_keyword_intents STRING OPTIONS(description="Stringified JSON array of {label, probability} dicts for alternative intents, with probabilities preserved. NULL when the API returns no secondary intents."),
  language_code STRING OPTIONS(description="ISO language code the classification was run against. Endpoint is language-only — there is no location_code.")
"""

DATAFORSEO_LABS_DOMAIN_RANK_OVERVIEW_COLS = """\
  target STRING OPTIONS(description="Target domain as sent to DataForSEO (no scheme, no 'www.')."),
  location_code INT64 OPTIONS(description="DataForSEO location code (e.g., 2840 = United States)."),
  language_code STRING OPTIONS(description="Language code (e.g., en)."),
  organic_count INT64 OPTIONS(description="Organic block — number of keywords the domain ranks for in the top 100 SERP positions."),
  organic_etv FLOAT64 OPTIONS(description="Organic block — estimated monthly organic traffic volume."),
  organic_estimated_paid_traffic_cost FLOAT64 OPTIONS(description="Organic block — estimated cost (USD) to buy equivalent organic traffic via paid ads."),
  organic_is_new INT64 OPTIONS(description="Organic block — count of keywords newly ranked since the previous snapshot. Integer counter despite the is_* prefix — not a boolean."),
  organic_is_up INT64 OPTIONS(description="Organic block — count of keywords whose rank improved. Integer counter, not boolean."),
  organic_is_down INT64 OPTIONS(description="Organic block — count of keywords whose rank dropped. Integer counter, not boolean."),
  organic_is_lost INT64 OPTIONS(description="Organic block — count of keywords lost from the ranked set. Integer counter, not boolean."),
  organic_pos_1 INT64 OPTIONS(description="Organic block — number of keywords ranking at position #1."),
  organic_pos_2_3 INT64 OPTIONS(description="Organic block — number of keywords ranking in positions 2-3."),
  organic_pos_4_10 INT64 OPTIONS(description="Organic block — number of keywords ranking in positions 4-10 (rest of page 1)."),
  organic_pos_11_20 INT64 OPTIONS(description="Organic block — number of keywords ranking in positions 11-20 (page 2)."),
  organic_pos_21_30 INT64 OPTIONS(description="Organic block — number of keywords ranking in positions 21-30."),
  organic_pos_31_40 INT64 OPTIONS(description="Organic block — number of keywords ranking in positions 31-40."),
  organic_pos_41_50 INT64 OPTIONS(description="Organic block — number of keywords ranking in positions 41-50."),
  organic_pos_51_60 INT64 OPTIONS(description="Organic block — number of keywords ranking in positions 51-60."),
  organic_pos_61_70 INT64 OPTIONS(description="Organic block — number of keywords ranking in positions 61-70."),
  organic_pos_71_80 INT64 OPTIONS(description="Organic block — number of keywords ranking in positions 71-80."),
  organic_pos_81_90 INT64 OPTIONS(description="Organic block — number of keywords ranking in positions 81-90."),
  organic_pos_91_100 INT64 OPTIONS(description="Organic block — number of keywords ranking in positions 91-100."),
  paid_count INT64 OPTIONS(description="Paid block — number of keywords the domain runs paid (Google Ads) results for."),
  paid_etv FLOAT64 OPTIONS(description="Paid block — estimated monthly paid traffic volume from those ads."),
  paid_estimated_paid_traffic_cost FLOAT64 OPTIONS(description="Paid block — estimated monthly ad spend (USD) to sustain that paid traffic."),
  paid_is_new INT64 OPTIONS(description="Paid block — count of paid keywords newly appearing. Integer counter, not boolean."),
  paid_is_up INT64 OPTIONS(description="Paid block — count of paid keywords whose ad position improved. Integer counter, not boolean."),
  paid_is_down INT64 OPTIONS(description="Paid block — count of paid keywords whose ad position dropped. Integer counter, not boolean."),
  paid_is_lost INT64 OPTIONS(description="Paid block — count of paid keywords lost from the set. Integer counter, not boolean.")
"""

KEYWORDS_DATA_SEARCH_VOLUME_COLS = """\
  keyword STRING OPTIONS(description="The keyword phrase that was queried."),
  search_volume INT64 OPTIONS(description="Average monthly search volume over the trailing 12 months (Google Ads estimate)."),
  location_code INT64 OPTIONS(description="DataForSEO numeric location code for the market the volume applies to (e.g., 2840 = United States)."),
  cpc FLOAT64 OPTIONS(description="Average cost per click in USD for ads targeting this keyword."),
  competition STRING OPTIONS(description="Google Ads advertiser-competition bucket; enum of LOW, MEDIUM, HIGH (may be NULL if unavailable)."),
  competition_index INT64 OPTIONS(description="Granular competition score on a 0-100 scale (higher = more advertiser competition)."),
  low_top_of_page_bid FLOAT64 OPTIONS(description="Low end of the bid range (USD) required to place an ad at the top of the first search results page."),
  high_top_of_page_bid FLOAT64 OPTIONS(description="High end of the bid range (USD) required to place an ad at the top of the first search results page."),
  monthly_searches STRING OPTIONS(description="Stringified JSON array of the last 12 months of search history, each element {year, month, search_volume}.")
"""


MIGRATIONS: list[Migration] = [
    Migration(
        old_name="backlinks_backlinks_live",
        new_name="backlinks-backlinks",
        new_schema=METADATA_BLOCK_SQL + BACKLINKS_BACKLINKS_COLS,
    ),
    Migration(
        old_name="backlinks_bulk_pages_summary_live",
        new_name="backlinks-bulk_pages_summary",
        new_schema=METADATA_BLOCK_SQL + BACKLINKS_BULK_PAGES_SUMMARY_COLS,
        drop_project_id=True,
    ),
    Migration(
        old_name="backlinks_summary_live",
        new_name="backlinks-summary",
        new_schema=METADATA_BLOCK_SQL + BACKLINKS_SUMMARY_COLS,
        drop_project_id=True,
    ),
    Migration(
        old_name="serp_google_organic_live_advanced",
        new_name="serp-google-organic",
        new_schema=METADATA_BLOCK_SQL + SERP_GOOGLE_ORGANIC_COLS,
        drop_project_id=True,
    ),
    Migration(
        old_name="google_keyword-suggestions_live",
        new_name="dataforseo_labs-google-keyword_suggestions",
        new_schema=METADATA_BLOCK_SQL + DATAFORSEO_LABS_KEYWORD_SUGGESTIONS_COLS,
    ),
    Migration(
        old_name="google_related-keywords_live",
        new_name="dataforseo_labs-google-related_keywords",
        new_schema=METADATA_BLOCK_SQL + DATAFORSEO_LABS_RELATED_KEYWORDS_COLS,
    ),
    Migration(
        # In-place schema update only — name already canonical
        old_name="dataforseo_labs-google-ranked_keywords",
        new_name="dataforseo_labs-google-ranked_keywords",
        new_schema=METADATA_BLOCK_SQL + DATAFORSEO_LABS_RANKED_KEYWORDS_COLS,
    ),
    Migration(
        old_name="dataforseo_labs_google_keyword_overview",
        new_name="dataforseo_labs-google-keyword_overview",
        new_schema=METADATA_BLOCK_SQL + DATAFORSEO_LABS_KEYWORD_OVERVIEW_COLS,
    ),
    Migration(
        old_name="dataforseo_labs_google_search_intent",
        new_name="dataforseo_labs-google-search_intent",
        new_schema=METADATA_BLOCK_SQL + DATAFORSEO_LABS_SEARCH_INTENT_COLS,
    ),
    Migration(
        # New table — no old_name
        old_name=None,
        new_name="dataforseo_labs-google-domain_rank_overview",
        new_schema=METADATA_BLOCK_SQL + DATAFORSEO_LABS_DOMAIN_RANK_OVERVIEW_COLS,
    ),
    Migration(
        old_name="keyword_data-google_ads-search_volume",
        new_name="keywords_data-google_ads-search_volume",
        new_schema=METADATA_BLOCK_SQL + KEYWORDS_DATA_SEARCH_VOLUME_COLS,
    ),
]
